### ISSUE TITLE
Temporary directory not cleared

### ISSUE THREAD

**Issue by tishun** [Codarama/diet-engine#29]
After each run the old extracted dependencies are still there and build up the pool

By the way - weren't we inspecting the JAR files without extracting them? Weird. Have to check.

Assign to me.

**Comment by ayld** [comment]
We're not extracting , there was an issue about removing extraction logic and it's done.

**Comment by ayld** [comment]
#25

**Comment by tishun** [comment]
Ignore that, my local repo is in disarray, I synced to latest
