### ISSUE TITLE
Add statistics when minimization is done

### ISSUE THREAD

**Issue by ayld** [Codarama/diet-engine#4]
We could print something like:

[INFO] You were using: 453 jars (322 transitive), with 5321 classes.
[INFO] Now using: 1 jar, 122 classes.

(these are real statistics from one of the tests btw ;) )

This can help the feel (lol!).

**Comment by ayld** [comment]
Whats not ready on this btw? I had a look at the API/current impl and it looked alright.

**Comment by tishun** [comment]
Not sure anymore ... lets close it for now.
