### ISSUE TITLE
Improve jar extraction speed.

### ISSUE THREAD

**Issue by ayld** [Codarama/diet-engine#7]
We should see if there's a way to speed up jar extraction or better yet if there's a way to remove it altogether.

I'm thinking of mounting the jars (they're zips so it should be possible) or streaming them somehow.

**Comment by tishun** [comment]
Started work on a prototype. 

I think we need to skip exploding the jars altogether. Instead we should modify the matchers to examine elements from the jar (zip) archive and then, when and only when we have a match, we would extract it and place it in our target directory.

This would speed up the execution time A LOT. Scientifically speaking :smiley_cat: 

Currently one of my test projects requires more than 15 minutes to minimize ... and it is a small project

**Comment by ayld** [comment]
Are you running it over a full /m2 repo? It shouldn't be slow for anything around ~100 jars as dependencies.

**Comment by tishun** [comment]
Why, yes, I was.

Still ... would be nice to speed it up

**Comment by ayld** [comment]
Oh yes speed up is definitely necessary :) but my main idea about the large repos was for the build tool plugins to handle them (our maven/gradle/ant plugins).

**Comment by ayld** [comment]
No need for this as we're no longer extracting jars as per [0ea527da1c51a7c0a26bbabe5d62270719a36831](https://github.com/Codarama/diet-engine/commit/0ea527da1c51a7c0a26bbabe5d62270719a36831).
