### ISSUE TITLE
Deploy current last release to a public Maven repo

### ISSUE THREAD

**Issue by ayld** [Codarama/diet-engine#8]
We need to deploy the last release to a publicly visible repo (meaning Nexus) so that people can easily reference it in their POM and not have to download the .jar and `mvn install` it manually.

We can either deploy a free [Nexus](http://www.sonatype.org/nexus/) on [Heroku](https://www.heroku.com/) for instance or [host a maven repo directly on GitHub](http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github) which looks easy.

**Comment by tishun** [comment]
So, after reading the instructions (yes, yes, this should have been the first thing to do, I know) the SonaType guys are actually also providing support for internal (snapshot) releases, so I will add all the required settings to the POM files and we should be ready to go!

Ref : http://central.sonatype.org/pages/ossrh-guide.html
Ref : https://www.youtube.com/watch?v=dXR4pJ_zS-0&feature=youtu.be

**Comment by tishun** [comment]
Success!!!

https://oss.sonatype.org/content/repositories/snapshots/org/codarama/diet/diet-engine/0.6.0-SNAPSHOT/

**Comment by tishun** [comment]
Success!!!

https://oss.sonatype.org/content/repositories/snapshots/org/codarama/diet/diet-maven-mojo/0.0.1-SNAPSHOT/

**Comment by tishun** [comment]
Here is the latest state of affairs :
* both Mojo and Engine are set up for release / snapshot builds
* to release we remove the -SNAPSHOT from the version and call mvn deploy
* to release snapshot we only call mvn deploy
* to release one needs to have in his settings.xml file proper configuration for both PGP keys and SonaType account

The current released versions are:
0.6.0 for diet-engine, see https://search.maven.org/#search|ga|1|a%3A"diet-engine"
0.0.1 for diet-mven-mojo, see https://search.maven.org/#search|ga|1|a%3A"diet-maven-mojo"
